# Generated by Django 6.0.3 on 2026-03-29 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'teacher')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
