# Generated by Django 6.0.3 on 2026-03-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_production_academic_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated for students: DEPT + year + sequence.', max_length=32, null=True, unique=True),
        ),
    ]
