from django.urls import path

from . import views, views_extended, views_groups

app_name = 'reports'

urlpatterns = [
    path('activity-log/', views_extended.activity_log_viewer, name='activity_log'),
    path('leaderboard/', views_extended.leaderboard, name='leaderboard'),
    path('submission-tracking/', views_extended.submission_tracking, name='submission_tracking'),
    path('teacher-workload/', views_extended.teacher_workload, name='teacher_workload'),
    path('extensions/', views_extended.extension_queue, name='extension_queue'),
    path('extensions/<int:pk>/resolve/', views_extended.extension_resolve, name='extension_resolve'),
    path('groups/', views_groups.project_groups_list, name='project_groups'),
    path('groups/create/', views_groups.project_group_create, name='project_group_create'),
    path('groups/manage/', views_groups.project_groups_admin, name='project_groups_admin'),
    path('groups/<int:pk>/assign-teacher/', views_groups.project_group_assign_teacher, name='project_group_assign_teacher'),
    path('submit/', views.submit_report, name='submit'),
    path('my/', views.my_reports, name='my_reports'),
    path('list/', views.report_list, name='list'),
    path('export/csv/', views.export_reports_csv, name='export_csv'),
    path('notifications/', views.notification_list, name='notifications'),
    path('notifications/mark-all-read/', views.notifications_mark_all_read, name='notifications_mark_all_read'),
    path('notifications/<int:pk>/open/', views.notification_open, name='notification_open'),
    path('notifications/<int:pk>/read/', views.notification_mark_read, name='notification_read'),
    path('bulk-action/', views.bulk_reports_action, name='bulk_action'),
    path('student/<slug:username>/', views.public_student_profile, name='public_student'),
    path('<int:pk>/compare/', views_extended.version_compare, name='version_compare'),
    path('<int:pk>/print/', views_extended.report_print, name='print'),
    path('<int:pk>/extension-request/', views_extended.request_deadline_extension, name='extension_request'),
    path('<int:pk>/pin/', views_extended.toggle_pin_report, name='toggle_pin'),
    path('certificate-template/analyze/', views.certificate_template_analyze, name='certificate_template_analyze'),
    path('certificate-template/preview-draft/', views.certificate_template_preview_draft, name='certificate_template_preview_draft'),
    path('certificate-template/preview/', views.certificate_template_preview, name='certificate_template_preview'),
    path('<int:pk>/member-profiles/', views.report_group_member_profiles, name='group_member_profiles'),
    path('<int:pk>/certificate-celebration/ack/', views.certificate_celebration_ack, name='certificate_celebration_ack'),
    path('<int:pk>/', views.report_detail, name='detail'),
    path('<int:pk>/pdf/', views.view_pdf, name='pdf'),
    path('<int:pk>/certificate/', views.download_certificate, name='certificate'),
    path('<int:pk>/comment/', views.add_comment, name='comment'),
    path('<int:pk>/delete/', views.delete_report, name='delete'),
    path('<int:pk>/restore/', views.restore_report, name='restore'),
    path('<int:pk>/resubmit/', views.resubmit_report, name='resubmit'),
    path('<int:pk>/teacher-approve/', views.teacher_approve, name='teacher_approve'),
    path('<int:pk>/teacher-reject/', views.teacher_reject, name='teacher_reject'),
    path('<int:pk>/admin-approve/', views.admin_approve, name='admin_approve'),
    path('<int:pk>/admin-reject/', views.admin_reject, name='admin_reject'),
    path('<int:pk>/assign-teacher/', views.assign_report_teacher, name='assign_teacher'),
    path('<int:pk>/bookmark/', views.toggle_bookmark, name='bookmark'),
    path('<int:pk>/reeval/', views.request_reevaluation, name='reeval_request'),
    path('reeval/<int:reeval_pk>/resolve/', views.resolve_reevaluation, name='reeval_resolve'),
]
