from __future__ import annotations

from typing import Any, Protocol

from django.db.models import QuerySet


class IReportRepository(Protocol):
    """Report persistence contract — implemented by infrastructure layer."""

    def get_by_id(self, id: int):
        ...

    def get_detail(self, id: int):
        ...

    def create(self, data: dict[str, Any]):
        ...

    def update(self, instance, data: dict[str, Any]):
        ...

    def get_queryset(self) -> QuerySet:
        ...

    def for_student(self, user) -> QuerySet:
        ...

    def for_teacher(self, user) -> QuerySet:
        ...

    def for_admin(self) -> QuerySet:
        ...

    def scoped_for_user(self, user) -> QuerySet:
        ...

    def apply_search_filters(self, qs: QuerySet, params: dict[str, Any]) -> QuerySet:
        ...

    def get_versions(self, report_id: int) -> QuerySet:
        ...

    def archive_current_file_as_version(self, report, next_version_number: int):
        ...

    def create_comment(self, report, user, message: str):
        ...

    def toggle_bookmark(self, user, report) -> bool:
        ...

    def is_bookmarked(self, user, report_id: int) -> bool:
        ...

    def record_recent_view(self, user, report) -> None:
        ...

    def save_rubric_scores(self, report, scores: dict[int, int]) -> None:
        ...

    def get_pending_reevaluation(self, report, student):
        ...

    def get_pending_reevaluations_for_report(self, report) -> QuerySet:
        ...

    def create_reevaluation_request(self, report, student, reason: str):
        ...

    def get_reevaluation_by_id(self, reeval_id: int):
        ...

    def resolve_reevaluation(self, reeval, *, status: str, updated_marks: int | None = None):
        ...

    def get_pending_extension(self, report, student):
        ...

    def create_extension_request(self, report, student, reason: str):
        ...

    def get_extension_by_id(self, extension_id: int):
        ...

    def resolve_extension(self, extension, *, status: str, reviewed_by, admin_note: str = ''):
        ...

    def get_default_rubric(self):
        ...

    def get_project_group(self, group_id: int):
        ...

    def get_system_settings(self):
        ...

    def update_system_settings(self, data: dict[str, Any]):
        ...

    def get_rubric_rows(self, report) -> list[dict[str, Any]]:
        ...

    def bulk_eligible_for_admin_approve(self, report_ids: list[int]) -> QuerySet:
        ...

    def get_reports_by_ids(self, report_ids: list[int]) -> QuerySet:
        ...

    def get_leaderboard_queryset(self, user, *, dept: str = '') -> QuerySet:
        ...

    def get_analytics_stats(self) -> dict[str, Any]:
        ...

    def get_submission_tracking(self) -> dict[str, Any]:
        ...

    def get_teacher_workload(self, teacher) -> dict[str, int]:
        ...

    def get_pending_extensions(self) -> QuerySet:
        ...
