from typing import Any, Protocol

from domain.accounts.entities import UserProfile


class IUserRepository(Protocol):
    def get_by_id(self, id: int) -> UserProfile | None: ...

    def get_by_username(self, username: str) -> UserProfile | None: ...

    def get_by_email(self, email: str) -> UserProfile | None: ...

    def create(self, data: dict[str, Any]) -> UserProfile: ...

    def update(self, id: int, data: dict[str, Any]) -> UserProfile: ...

    def delete(self, id: int) -> None: ...

    def filter_by_role(self, role: str) -> list[UserProfile]: ...

    def authenticate(self, username: str, password: str) -> UserProfile | None: ...

    def check_password(self, user_id: int, password: str) -> bool: ...

    def issue_jwt_tokens(self, user_id: int) -> dict[str, str]: ...

    def blacklist_refresh_token(self, refresh_token: str) -> None: ...

    def username_exists(self, username: str) -> bool: ...

    def email_exists(self, email: str) -> bool: ...

    def list_users(
        self,
        *,
        role: str | None = None,
        search: str = '',
        exclude_roles: list[str] | None = None,
    ) -> list[UserProfile]: ...

    def pending_students_for_teacher(self, teacher_id: int) -> list[UserProfile]: ...

    def get_user_detail(self, user_id: int) -> dict | None: ...

    def get_profile_detail(self, user_id: int) -> dict | None: ...

    def assign_teacher(self, student_id: int, teacher_id: int | None) -> UserProfile: ...

    def validate_new_password(self, user_id: int, password: str) -> None: ...

    def build_password_reset_token(self, user_id: int) -> tuple[str, str]: ...

    def reset_password_with_token(self, uid: str, token: str, new_password: str) -> UserProfile: ...

    def list_teachers(self, active_only: bool = True) -> list[UserProfile]: ...
