# Generated by Django 6.0.3 on 2026-03-29 10:14

import django.db.models.deletion
from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def copy_submission_settings(apps, schema_editor):
    Old = apps.get_model('reports', 'SubmissionSettings')
    Sys = apps.get_model('reports', 'SystemSettings')
    row = Old.objects.filter(pk=1).first()
    if row:
        Sys.objects.update_or_create(
            pk=1,
            defaults={
                'submission_deadline': row.deadline_date,
                'max_attempts': 5,
                'max_file_size_mb': 10,
            },
        )
    else:
        Sys.objects.get_or_create(
            pk=1,
            defaults={
                'submission_deadline': timezone.now() + timedelta(days=365),
                'max_attempts': 5,
                'max_file_size_mb': 10,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReEvaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('updated_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_deadline', models.DateTimeField(help_text='Submissions after this instant are marked late.')),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System settings',
            },
        ),
        migrations.RunPython(copy_submission_settings, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SubmissionSettings',
        ),
        migrations.AddField(
            model_name='report',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='marks',
            field=models.PositiveIntegerField(blank=True, help_text='Final marks (0–100), set by admin on approval.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='submission_round',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('final', 'Final')], db_index=True, default='review', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='teacher_marks',
            field=models.PositiveIntegerField(blank=True, help_text='Provisional marks from teacher.', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('teacher_approved', 'Teacher approved'), ('teacher_rejected', 'Teacher rejected'), ('admin_approved', 'Admin approved'), ('admin_rejected', 'Admin rejected'), ('deleted', 'Deleted'), ('restored', 'Restored'), ('comment', 'Comment added'), ('marks_set', 'Marks updated'), ('reeval_requested', 'Re-evaluation requested'), ('reeval_resolved', 'Re-evaluation resolved')], max_length=40),
        ),
        migrations.AddField(
            model_name='reevaluationrequest',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reevaluation_requests', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reevaluationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reevaluation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportbookmark',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reportbookmark',
            unique_together={('user', 'report')},
        ),
    ]
