# Generated by Django 5.2.15 on 2026-06-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_announcement_reportstatusdefinition_rubric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='certificate_verification_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique token for QR certificate verification.', max_length=64),
        ),
    ]
