# Generated by Django 5.2.15 on 2026-06-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_consolidate_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_analysis_json',
            field=models.JSONField(blank=True, default=dict, help_text='AI summary and suggested rubric scores for teacher review.'),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='extracted_text',
            field=models.TextField(blank=True, default='', help_text='Native text extracted from the submitted PDF.'),
        ),
        migrations.AddField(
            model_name='report',
            name='ocr_verification_json',
            field=models.JSONField(blank=True, default=dict, help_text='OCR vs native text verification metadata.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='teacher_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
