# Generated by Django 5.2.15 on 2026-06-14 10:19

import apps.reports.infrastructure.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_group_project_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='achievement_badge',
            field=models.ImageField(blank=True, null=True, upload_to=apps.reports.infrastructure.models.certificate_template_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='border_color',
            field=models.CharField(blank=True, default='#2d5a47', max_length=7),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='description_template',
            field=models.CharField(blank=True, default='has successfully completed the final project submission', max_length=260),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='design_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='name_color',
            field=models.CharField(blank=True, default='#2d5a47', max_length=7),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='name_font',
            field=models.CharField(blank=True, default='Helvetica-Bold', max_length=40),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='name_size',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.reports.infrastructure.models.certificate_template_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='organization_name',
            field=models.CharField(blank=True, default='ReportFlow', max_length=160),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='seal_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.reports.infrastructure.models.certificate_template_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.reports.infrastructure.models.certificate_template_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='tagline',
            field=models.CharField(blank=True, default='Official Project Completion Record', max_length=220),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.reports.infrastructure.models.certificate_template_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Background / reference image (PNG/JPG/WEBP).', null=True, upload_to=apps.reports.infrastructure.models.certificate_template_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='use_reference_background',
            field=models.BooleanField(default=True, help_text='When enabled, the background image fills the certificate.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_final_submission',
            field=models.BooleanField(default=False, help_text='Teacher marks this as the final submission; certificate is issued after admin approval.'),
        ),
    ]
